Repository GGUM-5/GGUM5-back, pull requests merged in 2024-10, with the labels that each got.

#3 [FEAT] 가톨릭대 도서관 열람실 인원 크롤러 개발
  build.gradle
  src/main/java/com/catspot/CatspotApplication.java
  src/main/java/com/catspot/crawler/CrawlerScheduler.java
  src/main/java/com/catspot/crawler/LibraryCrawler.java
  src/main/java/com/catspot/crawler/StudyPlace.java
  src/main/java/com/catspot/crawler/StudyPlaceRepository.java
  src/test/java/com/catspot/crawler/LibraryCrawlerTest.java
  src/test/java/com/catspot/crawler/StudyPlaceRepositoryTest.java
  src/test/java/com/catspot/crawler/StudyPlaceTest.java
Labels: enhancement

#5 [FEAT] Exception handling
  src/main/java/com/catspot/controller/TestController.java
  src/main/java/com/catspot/exceptionhandler/CommonErrorCode.java
  src/main/java/com/catspot/exceptionhandler/CustomException.java
  src/main/java/com/catspot/exceptionhandler/ErrorCode.java
  src/main/java/com/catspot/exceptionhandler/ErrorResponse.java
  src/main/java/com/catspot/exceptionhandler/GlobalExceptionHandler.java
Labels: enhancement

#8 [FEAT] main에 push될 때만 배포되도록 수정
  .github/workflows/gradle.yml
Labels: 👷cicd

#12 [REFACTOR] 예외 처리 리팩토링 및 테스트 추가
  src/main/java/com/catspot/controller/TestController.java
  src/main/java/com/catspot/exceptionhandler/GlobalExceptionHandler.java
  src/test/java/com/catspot/exceptionhandler/GlobalExceptionHandlerTest.java
Labels: ⚡refactor, 📈test

#13 [FEAT] 개설과목리스트 불러오기 및 파싱 기능 개발
  build.gradle
  src/main/java/com/catspot/entity/Classroom.java
  src/main/java/com/catspot/entity/SessionTime.java
  src/main/java/com/catspot/entity/TimeTable.java
  src/main/java/com/catspot/excel/ExcelDataInitializer.java
  src/main/java/com/catspot/excel/ExcelParser.java
  src/main/java/com/catspot/excel/ExcelReader.java
  src/main/java/com/catspot/excel/Schedule.java
  src/main/java/com/catspot/repository/ClassroomRepository.java
  src/main/java/com/catspot/repository/SessionTimeRepository.java
  src/main/java/com/catspot/repository/TimeTableRepository.java
  src/main/resources/course/개설과목리스트_20241019175059.xlsx
  src/test/java/com/catspot/excel/ExcelParserTest.java
  src/test/java/com/catspot/excel/ExcelReaderTest.java
Labels: ✨feature

#14 [FEAT] 열람실 잔여좌석 조회용 API 개발
  build.gradle
  src/main/java/com/catspot/crawler/CrawlerScheduler.java
  src/main/java/com/catspot/crawler/LibraryCrawler.java
  src/main/java/com/catspot/studyplace/StudyPlace.java
  src/main/java/com/catspot/studyplace/StudyPlaceController.java
  src/main/java/com/catspot/studyplace/StudyPlaceDto.java
  src/main/java/com/catspot/studyplace/StudyPlaceMapper.java
  src/main/java/com/catspot/studyplace/StudyPlaceRepository.java
  src/main/java/com/catspot/studyplace/StudyPlaceResponse.java
  src/test/java/com/catspot/crawler/LibraryCrawlerTest.java
  src/test/java/com/catspot/studyplace/StudyPlaceControllerTest.java
  src/test/java/com/catspot/studyplace/StudyPlaceDtoTest.java
  src/test/java/com/catspot/studyplace/StudyPlaceMapperTest.java
  src/test/java/com/catspot/studyplace/StudyPlaceRepositoryTest.java
  src/test/java/com/catspot/studyplace/StudyPlaceResponseTest.java
  src/test/java/com/catspot/studyplace/StudyPlaceTest.java
Labels: ✨feature

#16 [FEAT] 건물 및 층 별 강의실 상태 조회 API 구현
  src/main/java/com/catspot/controller/ClassroomController.java
  src/main/java/com/catspot/controller/TimeTableController.java
  src/main/java/com/catspot/dto/request/ClassroomRequestDto.java
  src/main/java/com/catspot/dto/request/TimeTableRequestDto.java
  src/main/java/com/catspot/dto/response/ClassroomGetResponseDto.java
  src/main/java/com/catspot/dto/response/SessionTimeGetResponseDto.java
  src/main/java/com/catspot/dto/response/TimeTableGetResponse.java
  src/main/java/com/catspot/entity/SessionTime.java
  src/main/java/com/catspot/entity/TimeTable.java
  src/main/java/com/catspot/repository/ClassroomRepository.java
  src/main/java/com/catspot/repository/TimeTableRepository.java
  src/main/java/com/catspot/service/ClassroomService.java
  src/main/java/com/catspot/service/TimeTableService.java
  src/main/java/com/catspot/util/TimeCalculator.java
  src/test/java/com/catspot/service/ClassroomServiceTest.java
  src/test/java/com/catspot/service/TimeTableServiceTest.java
Labels: ✨feature

#18 [FIX] CORS 설정 변경
  src/main/java/com/catspot/cors/WebMvcConfig.java
Labels: 🐛fix

#20 [FIX] CORS POST 허용
  src/main/java/com/catspot/cors/WebMvcConfig.java
Labels: 🐛fix

#23 [REFACTOR] 크롤러 예외 처리 추가
  src/main/java/com/catspot/crawler/CrawlerScheduler.java
  src/main/java/com/catspot/crawler/LibraryCrawler.java
  src/main/java/com/catspot/exceptionhandler/CommonErrorCode.java
  src/main/java/com/catspot/studyplace/StudyPlaceController.java
  src/test/java/com/catspot/crawler/LibraryCrawlerTest.java
Labels: ⚡refactor

#26 [REFACTOR] ExcelReader Refactoring
  src/main/java/com/catspot/excel/ExcelReader.java
Labels: ⚡refactor

#32 [TEST] ClassroomService Test Coverage 100
  src/test/java/com/catspot/service/ClassroomServiceTest.java
Labels: 📈test

#36 [TEST] 시간계산기 테스트 커버리지 100%
  src/test/java/com/catspot/util/TimeCalculatorTest.java
Labels: 📈test

#40 Test/controller test
  src/test/java/com/catspot/controller/ClassroomControllerTest.java
  src/test/java/com/catspot/controller/TimeTableControllerTest.java
Labels: 📈test

#43 [TEST] Crawler 테스트 커버리지 100%
  src/main/java/com/catspot/crawler/CrawlerScheduler.java
  src/main/java/com/catspot/crawler/JsoupHelper.java
  src/main/java/com/catspot/crawler/LibraryCrawler.java
  src/test/java/com/catspot/crawler/CrawlerSchedulerTest.java
  src/test/java/com/catspot/crawler/JsoupHelperTest.java
  src/test/java/com/catspot/crawler/LibraryCrawlerTest.java
Labels: 📈test

#45 [FEAT] discord 메신저 기능 추가
  src/main/java/com/catspot/discord/DiscordConfig.java
  src/main/java/com/catspot/discord/DiscordController.java
  src/main/java/com/catspot/discord/DiscordWebhookRequest.java
Labels: ✨feature
